"""add profile_favourites

Revision ID: 2874316c7de7
Revises: 1e570d034858
Create Date: 2026-05-06 16:11:22.733548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2874316c7de7'
down_revision = '1e570d034858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_favorites',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('fav_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fav_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'fav_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_favorites')
    # ### end Alembic commands ###
